server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: abc123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher